apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`prometheus.local`)
      priority: 10
      services:
        - name: kube-prometheus-stack-prometheus
          port: 9090
