apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.local`)
      priority: 10
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
